from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(325, 325))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(350, 350))
        self.centralwidget.setObjectName("centralwidget")
        self.VOTING = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.VOTING.setGeometry(QtCore.QRect(10, 0, 300, 261))
        self.VOTING.setMinimumSize(QtCore.QSize(200, 200))
        self.VOTING.setMaximumSize(QtCore.QSize(300, 300))
        self.VOTING.setObjectName("VOTING")
        self.label = QtWidgets.QLabel(parent=self.VOTING)
        self.label.setGeometry(QtCore.QRect(10, 20, 35, 10))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.VOTING)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.VOTING)
        self.label_2.setGeometry(QtCore.QRect(40, 54, 111, 21))
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.VOTING)
        self.radioButton.setGeometry(QtCore.QRect(60, 80, 62, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.VOTING)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 100, 62, 14))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_4 = QtWidgets.QLabel(parent=self.VOTING)
        self.label_4.setGeometry(QtCore.QRect(60, 180, 111, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.VOTING)
        self.pushButton.setGeometry(QtCore.QRect(60, 130, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=self.VOTING)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 91, 31))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.VOTING)
        self.label_6.setGeometry(QtCore.QRect(150, 220, 121, 31))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.VOTING.setTitle(_translate("MainWindow", "VOTING MENU"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "CANADIATES"))
        self.radioButton.setText(_translate("MainWindow", "  Jane"))
        self.radioButton_2.setText(_translate("MainWindow", "Jone"))
        self.pushButton.setText(_translate("MainWindow", "Submit Vote"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
